#!/bin/bash

# outputs all local branches except master and the current one
function get_local_branches() {
    local current_branch="$(git branch --no-color | grep -E '^\*' | cut -d' ' -f2)"
    git for-each-ref refs/heads | cut -d/ -f3 | grep -Ev "^(${current_branch}|master)$"
}

get_local_branches | while read -r branch; do
    echo "Latest commit on branch '${branch}' is:"
    git log --pretty=format:"%C(yellow)%h %C(cyan)%cd %Creset%s" --stat --date=relative -1 "${branch}"

    echo
    read -rp "Delete branch '${branch}' (y/n)? " ans < /dev/tty
    case "${ans}" in
        y|Y )
            echo Deleting...
            git branch -D "${branch}" ;;

        * )
            echo Skipping... ;;
    esac
    echo
done

echo Done
